@domain:signatures @m2 @REQ-SIG-036 @spec(api_signatures.md#2821-when-to-use-addsignature-low-level)
Feature: When to Use AddSignature Low-Level

  @REQ-SIG-036 @happy
  Scenario: AddSignature is used when pre-computed signature data is available
    Given a NovusPack package
    And pre-computed signature data
    When AddSignature is called with signature data
    Then signature is added to package
    And function provides direct control over signature addition
    And function accepts signature type, data, and flags
    And function follows low-level signature addition pattern

  @REQ-SIG-036 @happy
  Scenario: AddSignature is used for custom signature generation logic
    Given a NovusPack package
    And custom signature generation logic
    When AddSignature is used
    Then custom signature generation can be implemented
    And signature data can be generated externally
    And signature can be added using low-level interface
    And direct control over signature addition is provided

  @REQ-SIG-036 @happy
  Scenario: AddSignature is used for external signature services
    Given a NovusPack package
    And external signature service
    When signature is generated by external service
    Then AddSignature can add pre-computed signature
    And signature from external service can be integrated
    And low-level interface enables external service integration

  @REQ-SIG-036 @error
  Scenario: AddSignature handles invalid signature data
    Given a NovusPack package
    And invalid signature data
    When AddSignature is called with invalid data
    Then structured error is returned
    And error indicates invalid signature data
    And error follows structured error format
