#!/usr/bin/env python3
"""
Shared utilities for validation scripts.

This module provides common functionality for all validation scripts,
including color support, standardized output formatting, and helper functions.

Facade: re-exports from lib.validation for backward compatibility.
Implementation lives in scripts/lib/validation/ (_core, _output, _fs, _markdown).
"""

from lib.validation import (
    DOCS_DIR,
    FEATURES_DIR,
    REQUIREMENTS_DIR,
    TECH_SPECS_DIR,
    COLOR_GREEN,
    COLOR_RED,
    COLOR_RESET,
    COLOR_YELLOW,
    SEPARATOR_WIDTH,
    OutputBuilder,
    ValidationIssue,
    calculate_label_width,
    colorize,
    format_issue_message,
    format_summary_line,
    parse_no_color_flag,
    supports_color,
    FileContentCache,
    find_feature_files,
    find_markdown_files,
    is_in_dot_directory,
    HeadingContext,
    ProseSection,
    build_heading_hierarchy,
    contains_url,
    count_sentences,
    extract_headings,
    extract_headings_from_file,
    extract_headings_with_anchors,
    extract_h2_plus_headings_with_sections,
    extract_headings_with_section_numbers,
    find_heading_before_line,
    find_heading_for_code_block,
    generate_anchor_from_heading,
    get_backticks_error_message,
    get_common_abbreviations,
    get_subheadings,
    has_backticks,
    has_code_blocks,
    is_organizational_heading,
    is_safe_path,
    remove_backticks_keep_content,
    validate_anchor,
    validate_file_name,
    validate_spec_file_name,
    get_validation_exit_code,
    get_workspace_root,
    import_module_with_fallback,
    parse_paths,
)

__all__ = [
    "DOCS_DIR",
    "FEATURES_DIR",
    "REQUIREMENTS_DIR",
    "TECH_SPECS_DIR",
    "COLOR_GREEN",
    "COLOR_RED",
    "COLOR_RESET",
    "COLOR_YELLOW",
    "SEPARATOR_WIDTH",
    "OutputBuilder",
    "ValidationIssue",
    "calculate_label_width",
    "colorize",
    "format_issue_message",
    "format_summary_line",
    "parse_no_color_flag",
    "supports_color",
    "FileContentCache",
    "find_feature_files",
    "find_markdown_files",
    "is_in_dot_directory",
    "HeadingContext",
    "ProseSection",
    "build_heading_hierarchy",
    "contains_url",
    "count_sentences",
    "extract_headings",
    "extract_headings_from_file",
    "extract_headings_with_anchors",
    "extract_h2_plus_headings_with_sections",
    "extract_headings_with_section_numbers",
    "find_heading_before_line",
    "find_heading_for_code_block",
    "generate_anchor_from_heading",
    "get_backticks_error_message",
    "get_common_abbreviations",
    "get_subheadings",
    "has_backticks",
    "has_code_blocks",
    "is_organizational_heading",
    "is_safe_path",
    "remove_backticks_keep_content",
    "validate_anchor",
    "validate_file_name",
    "validate_spec_file_name",
    "get_validation_exit_code",
    "get_workspace_root",
    "import_module_with_fallback",
    "parse_paths",
]
