# golangci-lint configuration
# Matches api/go strategy: contextcheck, dupl, gocyclo, gocritic, goconst, gocognit.
# Ensures context propagation and code quality standards.

version: "2"

linters:
  enable:
    - contextcheck
    - dupl          # Code duplication detection
    - gocyclo       # Cyclomatic complexity
    - gocritic      # Code critique and code smells
    - goconst       # Constant usage
    - gocognit      # Cognitive complexity
  settings:
    dupl:
      threshold: 50
    gocyclo:
      min-complexity: 15
    gocritic:
      enabled-tags:
        - diagnostic
        - experimental
        - opinionated
        - performance
        - style
      disabled-checks:
        - dupImport
    goconst:
      min-len: 3
    gocognit:
      min-complexity: 15
